/* Auth */
export const AUTH_FIRST_NAME_CHANGED = 'auth_first_name_changed'
export const AUTH_LAST_NAME_CHANGED = 'auth_last_name_changed'
export const AUTH_EMAIL_CHANGED = 'auth_email_changed'
export const AUTH_PASSWORD_CHANGED = 'auth_password_changed'
export const LOGIN_USER_SUCCESS = 'login_user_success'
export const LOGIN_USER_FAIL = 'login_user_fail'
export const LOGIN_USER = 'login_user'
export const SIGNUP_USER_SUCCESS = 'signup_user_success'
export const SIGNUP_USER_FAIL = 'signup_user_fail'
export const SIGNUP_USER = 'signup_user'
export const SIGNUP_CLICKED = 'signup_clicked'
export const SIGNUP_LEFT_CLICKED = 'signup_left_clicked'

/* Chat Create */
export const CHAT_EMAIL_CHANGED = 'chat_email_changed'
export const CREATE_CHAT = 'create_chat'
export const CREATE_CHAT_FAIL = 'create_chat_fail'
export const CREATE_CHAT_SUCCESS = 'create_chat_success'

/* Chat List */
export const RENDER_CHAT = 'render_chat'
export const RENDER_CHAT_DONE = 'render_chat_done'
export const RENDER_LIST = 'render_list'
export const RENDER_LIST_SUCCESS = 'render_list_success'
export const RENDER_LIST_FAIL = 'render_list_fail'

/* Focus Chat */
export const RENDER_CHAT_SUCCESS = 'render_chat_success'
export const RENDER_CHAT_SUCCESS_WITH_PUBLIC_KEY = 'render_chat_success_with_public_key'
export const RENDER_CHAT_SUCCESS_WITH_NO_PUBLIC_KEY = 'render_chat_success_with_no_public_key'
export const RENDER_CHAT_FAIL = 'render_chat_fail'
export const CHAT_INPUT_CHANGED = 'chat_input_changed'
export const PRIVATE_KEY_FILE_NAME_CHANGED = 'private_key_file_name_changed'
export const PUBLIC_KEY_FILE_NAME_CHANGED = 'public_key_file_name_changed'
export const FIND_KEYS = 'find_keys'
export const FIND_KEYS_SUCCESS = 'find_keys_success'
export const FIND_KEYS_FAIL = 'find_keys_fail'
export const FIND_PUBLIC_KEY_SUCCESS = 'find_public_key_success'
export const FIND_PUBLIC_KEY_FAIL = 'find_public_key_fail'
export const MESSAGE_SENT_SUCCESSFUL = 'message_sent_successful'
export const MESSAGE_SENT_FAIL = 'message_sent_fail'
export const EMPTY_KEYS = 'empty_keys'